
package org.blackjackj.wslab.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProductNotFoundException", targetNamespace = "http://service.wslab.blackjackj.org/")
public class ProductNotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProductNotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProductNotFoundException(String message, ProductNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProductNotFoundException(String message, ProductNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.blackjackj.wslab.service.ProductNotFoundFault
     */
    public ProductNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
