
package org.blackjackj.wslab.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.wslab.blackjackj.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param id
     * @throws ProductNotFoundException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProductById", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.DeleteProductById")
    @ResponseWrapper(localName = "deleteProductByIdResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.DeleteProductByIdResponse")
    public void deleteProductById(
        @WebParam(name = "id", targetNamespace = "")
        Long id)
        throws ProductNotFoundException
    ;

    /**
     * 
     * @param updateTO
     * @throws ProductUpdateException
     * @throws ProductNotFoundException
     */
    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.UpdateProductResponse")
    public void updateProduct(
        @WebParam(name = "updateTO", targetNamespace = "")
        ProductUpdateTO updateTO)
        throws ProductNotFoundException, ProductUpdateException
    ;

    /**
     * 
     * @param createTO
     * @return
     *     returns java.lang.Long
     * @throws ProductCreateException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.CreateProductResponse")
    public Long createProduct(
        @WebParam(name = "createTO", targetNamespace = "")
        ProductCreateTO createTO)
        throws ProductCreateException
    ;

    /**
     * 
     * @param searchTO
     * @return
     *     returns java.util.List<org.blackjackj.wslab.service.Product>
     * @throws ProductSearchException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.GetProductsResponse")
    public List<Product> getProducts(
        @WebParam(name = "searchTO", targetNamespace = "")
        ProductSearchTO searchTO)
        throws ProductSearchException
    ;

}
