
package org.blackjackj.wslab.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductWebService", targetNamespace = "http://service.wslab.blackjackj.org/", wsdlLocation = "http://localhost:8080/ProductService?wsdl")
public class ProductWebService
    extends Service
{

    private final static URL PRODUCTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTWEBSERVICE_EXCEPTION;
    private final static QName PRODUCTWEBSERVICE_QNAME = new QName("http://service.wslab.blackjackj.org/", "ProductWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProductService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTWEBSERVICE_WSDL_LOCATION = url;
        PRODUCTWEBSERVICE_EXCEPTION = e;
    }

    public ProductWebService() {
        super(__getWsdlLocation(), PRODUCTWEBSERVICE_QNAME);
    }

    public ProductWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTWEBSERVICE_QNAME, features);
    }

    public ProductWebService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTWEBSERVICE_QNAME);
    }

    public ProductWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTWEBSERVICE_QNAME, features);
    }

    public ProductWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort() {
        return super.getPort(new QName("http://service.wslab.blackjackj.org/", "ProductServicePort"), ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wslab.blackjackj.org/", "ProductServicePort"), ProductService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTWEBSERVICE_EXCEPTION!= null) {
            throw PRODUCTWEBSERVICE_EXCEPTION;
        }
        return PRODUCTWEBSERVICE_WSDL_LOCATION;
    }

}
