
package org.blackjackj.wslab.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.wslab.blackjackj.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProductById", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.DeleteProductById")
    @ResponseWrapper(localName = "deleteProductByIdResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.DeleteProductByIdResponse")
    public boolean deleteProductById(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param price
     * @param name
     * @param description
     * @param manufacturer
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.CreateProductResponse")
    public Long createProduct(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "manufacturer", targetNamespace = "")
        String manufacturer,
        @WebParam(name = "price", targetNamespace = "")
        Double price,
        @WebParam(name = "description", targetNamespace = "")
        String description);

    /**
     * 
     * @param price
     * @param name
     * @param description
     * @param id
     * @param manufacturer
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.UpdateProductResponse")
    public boolean updateProduct(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "manufacturer", targetNamespace = "")
        String manufacturer,
        @WebParam(name = "price", targetNamespace = "")
        Double price,
        @WebParam(name = "description", targetNamespace = "")
        String description);

    /**
     * 
     * @param price
     * @param name
     * @param description
     * @param id
     * @param manufacturer
     * @return
     *     returns java.util.List<org.blackjackj.wslab.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.wslab.blackjackj.org/", className = "org.blackjackj.wslab.service.GetProductsResponse")
    public List<Product> getProducts(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "manufacturer", targetNamespace = "")
        String manufacturer,
        @WebParam(name = "price", targetNamespace = "")
        Double price,
        @WebParam(name = "description", targetNamespace = "")
        String description);

}
